## traefik.yml

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: dev-network
    defaultRule: Host(`{{ trimPrefix `/` .ContainerName }}.mamura.test`)

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

tls:
  certificates:
    - certFile: /etc/ssl/certs/selfsigned.crt
      keyFile: /etc/ssl/private/selfsigned.key
  options:
    default:
      sniStrict: false

api:
  insecure: true